[package]
name = "Marionette"
version = "0.1.0"
edition = "2018"
resolver = "2"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "marionette"
crate-type = ["cdylib"]

[dependencies]
