[package]
name = "Marionette"
version = "0.1.0"
edition = "2018"
resolver = "2"
publish = false

[lib]
name = "marionette"
crate-type = ["cdylib"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = false
